---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-18.04
  - name: centos-7.5

suites:
  - name: agent
    run_list:
      - recipe[test::fluentd]
  - name: bit
    run_list:
      - recipe[test::fluent_bit]
